# Generated by Django 5.0.6 on 2024-05-24 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('amo_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('main_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_group_of_project', to='group.group')),
            ],
        ),
    ]
